"""Generate a truthful, artifact-backed baseline status report."""

from __future__ import annotations

import json
import subprocess
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd


def _json(path: Path) -> dict:
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}


def _value(value: object) -> str:
    return "N/A" if value is None or value == "" else str(value)


def _recorded(mapping: dict, key: str) -> str:
    return _value(mapping[key]) if key in mapping else "NOT RUN"


def _verify_oof(path: Path) -> str:
    if not path.exists():
        return "NOT RUN"
    try:
        frame = pd.read_parquet(path, columns=["source1_entity_id", "candidate_entity_id", "score"])
        valid = {"source1_entity_id", "candidate_entity_id", "score"}.issubset(frame.columns)
        scores = pd.to_numeric(frame["score"], errors="coerce")
        valid = valid and not frame.duplicated(["source1_entity_id", "candidate_entity_id"]).any()
        valid = valid and scores.notna().all() and scores.map(__import__("math").isfinite).all()
        return "VERIFIED" if valid else "UNVERIFIED"
    except Exception:
        return "UNVERIFIED"


def _commit(repo: Path) -> str:
    try:
        return subprocess.check_output(["git", "-C", str(repo), "rev-parse", "HEAD"], text=True, stderr=subprocess.DEVNULL).strip()
    except Exception:
        return "unknown"


def generate_report(repo: Path, work_dir: Path, output_dir: Path) -> str:
    fold = _json(work_dir / "fold_summary.json")
    candidate = _json(work_dir / "train_candidate_report.json")
    metrics = _json(work_dir / "model" / "metrics.json")
    threshold = _json(work_dir / "model" / "best_threshold.json")
    oof = work_dir / "model" / "oof_predictions.parquet"
    verification = _json(work_dir / "fold_verification.json")
    matching = output_dir / "matching_results.tsv"
    candidate_pairs = output_dir / "candidate_pairs.tsv"
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    def exists(path: Path) -> str:
        return "RECORDED" if path.exists() else "NOT RUN"

    fold_status = verification.get("status", "UNVERIFIED") if verification else "UNVERIFIED"
    oof_status = _verify_oof(oof)
    submission_status = "NOT RUN"
    if matching.exists() and candidate_pairs.exists():
        submission_status = "UNVERIFIED (validator result not recorded)"

    lines = [
        "# Phase A — Real-Data Baseline Report", "", f"_Generated: {now}_", "",
        "> **Placeholder:** no real-data metrics are claimed by this committed report.",
        "> Run artifacts must be produced and independently verified before this report is updated.", "",
        "## Provenance", "", "| Field | Value |", "|---|---|",
        f"| Commit | `{_commit(repo)}` |", f"| Work directory | `{work_dir}` |",
        f"| Output directory | `{output_dir}` |", "| Real-data pipeline run | NOT RUN by Phase D implementation |", "",
        "## Verification status", "", "| Check | Status | Evidence |", "|---|---|---|",
        f"| Fold integrity | {fold_status} | `{work_dir / 'fold_verification.json'}` |",
        f"| OOF coverage | {oof_status} | `{oof}` |",
        f"| Submission validation | {submission_status} | matching and candidate outputs |",
        f"| Candidate recall | {_recorded(candidate, 'candidate_recall_overall')} | recorded candidate report only |",
        "", "## Baseline metrics", "", "| Metric | Value |", "|---|---|",
        f"| Macro F0.5 | {_recorded(metrics, 'macro_f05')} |",
        f"| Singleton accuracy | {_recorded(metrics, 'singleton_accuracy')} |",
        f"| Non-singleton Macro F0.5 | {_recorded(metrics, 'non_singleton_macro_f05')} |",
        f"| Selected threshold | {_recorded(threshold, 'threshold')} |",
        f"| Total candidate pairs | {_recorded(candidate, 'total_candidate_pairs')} |",
        f"| Fold summary artifact | {exists(work_dir / 'fold_summary.json')} |",
        "", "## Artifact checklist", "", "| Artifact | Status |", "|---|---|",
    ]
    artifacts = [
        work_dir / "folds.tsv", work_dir / "fold_summary.json", work_dir / "train_candidates.tsv",
        work_dir / "train_features.parquet", work_dir / "model" / "metrics.json",
        work_dir / "model" / "oof_predictions.parquet", matching, candidate_pairs,
    ]
    lines.extend(f"| `{path}` | {exists(path)} |" for path in artifacts)
    lines += ["", "---", "_Generated by `scripts/generate_baseline_report.py`; unavailable values are intentionally not fabricated._", ""]
    return "\n".join(lines)


def main() -> None:
    repo = Path(__file__).resolve().parents[1]
    work_dir = repo / "artifacts" / "h04_baseline_v2"
    output_dir = repo / "output" / "h04_baseline_v2"
    output = repo / "reports" / "baseline.md"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(generate_report(repo, work_dir, output_dir), encoding="utf-8")
    print(f"Report written to: {output}")


if __name__ == "__main__":
    main()
